"""
Django settings for meeting project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
import pymysql
pymysql.install_as_MySQLdb()

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = r"D:\BackupData\shane\Desktop\meeting\django-server-30-429202-4d4ce05e3a9b.json"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-srd6hr&yrlk4!vlpdd-tq@l)@02hd527k@=+8rt)*4oxty^%9+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 允許連線
ALLOWED_HOSTS = ["*"]


# 媒體文件存儲目錄
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # "line_bot",
    "login",
    # "employee",
    # "meet",
    'channels',
    'meeting'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meeting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meeting.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "USER": "django_db",
#         "NAME": "django_db",
#         "PASSWORD": "mgbPm@Fz)sf6lv3b", # 改成自己的密碼
#         "HOST": "127.0.0.1",
#         "PORT": "3306"
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True

# 媒體文件存儲目錄
MEDIA_ROOT = BASE_DIR / 'media'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# 設置靜態檔案ˋ(CSS、Javascripte、圖檔、文件...等檔案的路徑)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'public/assets'
STATICFILES_DIRS = [
    #BASE_DIR /  "meeting","static", 有可能影響到原static的環境設定，版面可能跑掉。
    os.path.join(BASE_DIR, "meeting","static"),
    #os.path.join(BASE_DIR, "meet","static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LINE_CHANNEL_ACCESS_TOKEN = "6M85NCPEx7rTCihI5DEqjsJH7MF5FTk7+15UBGP8bnFFKA56JWF25wEI9A1RoE0g+Tq/i4ciVgX/uFZgaHQS8ykMX57E9c6RhaCCBKS26p+gVQrRJCHrdT18H+Y97ypdnawZ1/nT2AVX+9zoIew6UwdB04t89/1O/w1cDnyilFU="
LINE_CHANNEL_SECRET = "df59bfa4ae39e4bbf9a1618218b96f1b"

#0814 新增
ASGI_APPLICATION = 'meeting.asgi.application'

#0814 新增for Channel
CHANNEL_LAYERS = {
    'default': {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    },
}

#0818 新增查看日誌
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}